"""Add osm_features table

Revision ID: 1402df3fc05d
Revises: c24cdddc1f74
Create Date: 2026-09-04 19:16:06.788842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '1402df3fc05d'
down_revision: Union[str, None] = 'c24cdddc1f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('osm_features',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('osm_type', sa.String(), nullable=False),
    sa.Column('osm_id', sa.BigInteger(), nullable=False),
    sa.Column('feature_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('raw_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_osm_features_geometry', 'osm_features', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_osm_features_type', 'osm_features', ['feature_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_osm_features_type', table_name='osm_features')
    op.drop_index('ix_osm_features_geometry', table_name='osm_features', postgresql_using='gist')
    op.drop_table('osm_features')
    # ### end Alembic commands ###
